volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - django_network

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - django_network

  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    networks:
      - django_network

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    restart: on-failure
    networks:
      - django_network

networks:
  django_network:
    driver: bridge